### ISSUE TITLE
Shorten from the front

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/abbreviate#14]
**Is your feature request related to a problem? Please describe.**
At the moment, the algorithm used starts from the last 'word' in the string and works backwards. This makes an assumption about how the string should be shortened that may not work for everyone.
A good option might be to shorten from the front instead.

**Describe the solution you'd like**
```
$ abbreviate --length 15 strategy-limited
strategy-ltd
$ abbreviate --from-front --length 15 strategy-limited
stg-limited
```

**Comment by andrysds** [comment]
hi! if you don't mind, i want to work on this issue.

**Comment by dnnrly** [comment]
Wow! Yes, feel free! Any contributions welcome.
