### ISSUE TITLE
Setting up a workflow for every pull request

### ISSUE THREAD

**Issue by VishalVatsal97** [dnnrly/abbreviate#20]
**Is your feature request related to a problem? Please describe.**
Creating a pull request does not check whether the change has broken current working test cases. Although it is encouraged to run all the tests before someone submits a PR but being double sure is good.

**Describe the solution you'd like**
Add a github workflow that will trigger all the tests to run when someone raises a PR.

**Describe alternatives you've considered**

**Additional context**

**Comment by dnnrly** [comment]
This is already configured:
https://github.com/dnnrly/abbreviate/blob/master/.github/workflows/pr.yml

I think there is an issue making pull requests across repos. Github doesn't know which account to charge the compute minutes to - so it just doesn't let you know.

What might work for you is writing your code on a branch of your fork and raising a PR on your own master.

**Comment by VishalVatsal97** [comment]
Ah.. I didn't see that yaml file, also there was no workflow executed when I raised a PR.

I will try what you suggested. 
Closing this issue.
