### ISSUE TITLE
Handle common prefixes/suffixes (when predefined word does not exist)

### ISSUE THREAD

**Issue by shirleyleu** [dnnrly/abbreviate#21]
**Is your feature request related to a problem? Please describe.**
Related to #13

**Describe the solution you'd like**
Add list of common prefixes and suffixes and their abbreviations (e.g. -ible -> bl)
When predefined word does not exist, attempt to remove common prefix or suffix (e.g. in-access-ible -> access-ible)
Look up remaining word again
Repeat prefix/suffix removal as many times as necessary (e.g. access-ible -> access)
Concatenate prefix abbreviation, word abbreviation, and suffix abbreviation (e.g. in-access-ible -> in-acc-bl)

cc @FungusHumungus

**Comment by dnnrly** [comment]
This is a fantastic idea!

There's another PR in progress that has the concept of 'strategy which selects an algorithm for shortening strings. I might see if I can get it moving along.

I think this would be a valuable addition.

**Comment by dnnrly** [comment]
Hi, I merge a change that allows users to select the strategy for abbreviations words. If you wanted to have a go at tackling this issue then it might be a little easier now.

**Comment by shirleyleu** [comment]
Thanks so much! @FungusHumungus and I will be working on this together. We're excited!
