### ISSUE TITLE
Remove functional words using a list of stopwords

### ISSUE THREAD

**Issue by sperez8** [dnnrly/abbreviate#33]
**Is your feature request related to a problem? Please describe.**
The English language has a lot of short connector words which have a grammatical function but don't necessarily provide meaning. Thus they can be omitted when creating abbreviations.

**Describe the solution you'd like**
A simple solution would be to save a list of stopwords and to have a flag that the user could use to remove them.

Here is an example:
`$ abbreviate snake "The strategy of limited science" --stopwords
tstg_ltd_sci`

versus the current behavior (so without the flag):
`$ abbreviate snake "The strategy of limited science" --stopwords
the_stg_of_ltd_sci`

**Additional context**
Initially we could curate our own list of stopwords. Eventually we could use this as a possible source:
https://github.com/bbalet/stopwords

**Comment by dnnrly** [comment]
Looks good, I'm interested to see what you come up with.

**Comment by leafoliage** [comment]
Hi, I'd like to work on this issue :D

**Comment by dnnrly** [comment]
Hi @leafoliage , I'm happy for anyone to work on these issues. I look forward to your PR!

**Comment by leafoliage** [comment]
Hi @dnnrly , I’ve opened a PR for this issue. Please review it :D
