### ISSUE TITLE
Add abbreviations for title case

### ISSUE THREAD

**Issue by amoghrajesh** [dnnrly/abbreviate#39]
**What word do you think needs abbreviating?**

We should add support for abbreviating using title casing. 
Title Case:
- Title case capitalizes the first letter of each word in a string, typically used for formatting titles, headings, or sentences and seperates it with space
Example: The Quick Brown Fox

**What should it be abbreviated to?**

Usage example:
```
$ abbreviate title prestrategy-limitedment
Prstg Ltdmnt
```

What's better?
NA

**Comment by amoghrajesh** [comment]
@dnnrly I would like to work on this if you think this is a valid issue to be fixed.

**Comment by dnnrly** [comment]
Yes, that would be good. I would recommend that you take a look at the acceptance tests first.

**Comment by amoghrajesh** [comment]
@dnnrly where are the acceptance tests? Are you talking about the CONTRIBUTING.md document?

**Comment by dnnrly** [comment]
It's the scenarios found here:

https://github.com/dnnrly/abbreviate/blob/master/test/features/cli.feature


Try adding a new scenario. This will check that your feature is working in the fully built app. Then, you'll have a target to aim for when you start the implementation.
